import { useState, useRef } from "react";
import { CATEGORIES, scoreColor, scoreHex } from "../data/scoring";
import { getGHSPictograms, getHPhraseDescription } from "../data/ghsData";
import GHSPictogramRow from "./GHSPictograms";
import RadarChart from "./RadarChart";

async function exportPDF(chemical, cardRef) {
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);

  const pdf = new jsPDF("p", "mm", "a4");
  const w = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let y = 15;

  // Title
  pdf.setFontSize(20);
  pdf.setFont(undefined, "bold");
  pdf.text(chemical.name, margin, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setFont(undefined, "normal");
  pdf.setTextColor(100);
  pdf.text(`CAS: ${chemical.cas}  |  Formula: ${chemical.formula}  |  MW: ${chemical.molecularWeight}`, margin, y);
  y += 5;
  pdf.text(`State: ${chemical.physicalState}  |  BP: ${chemical.boilingPoint}  |  Flash: ${chemical.flashPoint}`, margin, y);
  y += 8;

  // Overall score
  pdf.setTextColor(0);
  pdf.setFontSize(14);
  pdf.setFont(undefined, "bold");
  pdf.text(`Overall SSbD Score: ${chemical.overall}/5`, margin, y);
  y += 10;

  // Category scores
  pdf.setFontSize(11);
  pdf.text("Category Scores", margin, y);
  y += 6;
  pdf.setFontSize(9);
  pdf.setFont(undefined, "normal");
  const pdfIconMap = {
    acuteTox: "[ACUTE]", chronicCMR: "[CMR]", aquaticTox: "[AQUATIC]",
    persistence: "[PERSIST]", bioaccumulation: "[BIOACC]",
    physicalHaz: "[PHYSICAL]", endocrine: "[ENDOCRINE]",
  };
  CATEGORIES.forEach(({ key, label }) => {
    const s = chemical.scores[key];
    pdf.text(`${pdfIconMap[key] || ""} ${label}: ${s}/5`, margin + 2, y);
    y += 5;
  });
  y += 4;

  // H-phrases
  pdf.setFontSize(11);
  pdf.setFont(undefined, "bold");
  pdf.text("H-Phrases", margin, y);
  y += 6;
  pdf.setFontSize(9);
  pdf.setFont(undefined, "normal");
  chemical.hPhrases.forEach((h) => {
    const desc = getHPhraseDescription(h) || "";
    const line = `${h}: ${desc}`;
    const lines = pdf.splitTextToSize(line, w - margin * 2);
    lines.forEach((l) => {
      if (y > 270) { pdf.addPage(); y = 15; }
      pdf.text(l, margin + 2, y);
      y += 4.5;
    });
  });
  y += 4;

  // GHS pictograms
  const ghsIds = getGHSPictograms(chemical.hPhrases);
  if (ghsIds.length > 0) {
    pdf.setFontSize(11);
    pdf.setFont(undefined, "bold");
    pdf.text("GHS Pictograms: " + ghsIds.join(", "), margin, y);
    y += 8;
  }

  // Radar chart as image
  try {
    const radarEl = cardRef.current?.querySelector(".radar-chart-container");
    if (radarEl) {
      const canvas = await html2canvas(radarEl, { backgroundColor: "#0f172a", scale: 2 });
      const imgData = canvas.toDataURL("image/png");
      if (y > 180) { pdf.addPage(); y = 15; }
      const imgW = 100;
      const imgH = (canvas.height / canvas.width) * imgW;
      pdf.addImage(imgData, "PNG", (w - imgW) / 2, y, imgW, imgH);
      y += imgH + 8;
    }
  } catch (e) {
    // skip radar if capture fails
  }

  // Footer
  if (y > 270) { pdf.addPage(); y = 15; }
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(`Generated by ChemScreen — ${new Date().toLocaleDateString("sv-SE")}`, margin, 285);

  pdf.save(`ChemScreen_${chemical.name.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`);
}

export default function ChemicalCard({ chemical }) {
  const { name, cas, formula, hPhrases, scores, overall, physicalState, boilingPoint, flashPoint, molecularWeight } = chemical;
  const oc = scoreColor(overall);
  const ghsPictograms = getGHSPictograms(hPhrases);
  const [hPhrasesExpanded, setHPhrasesExpanded] = useState(false);
  const [activeTooltip, setActiveTooltip] = useState(null);
  const [exporting, setExporting] = useState(false);
  const cardRef = useRef(null);

  async function handleExportPDF() {
    setExporting(true);
    try {
      await exportPDF(chemical, cardRef);
    } catch (e) {
      console.error("PDF export failed:", e);
    }
    setExporting(false);
  }

  return (
    <div className="mt-6 animate-fadeIn" ref={cardRef}>
      {/* Header card */}
      <div className="bg-navy-800 border border-navy-600 rounded-2xl p-6">
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold">{name}</h2>
            <div className="flex flex-wrap gap-3 mt-1 text-sm text-navy-300">
              <span>CAS: <span className="text-cyan-400 font-mono font-semibold">{cas}</span></span>
              <span>Formula: <span className="text-navy-100">{formula}</span></span>
              <span>MW: <span className="text-navy-100">{molecularWeight}</span></span>
            </div>
            <div className="flex flex-wrap gap-3 mt-1 text-xs text-navy-400">
              <span>State: {physicalState}</span>
              <span>BP: {boilingPoint}</span>
              {flashPoint !== "N/A" && <span>Flash: {flashPoint}</span>}
            </div>
          </div>
          <div className="flex items-start gap-3 shrink-0">
            <button
              onClick={handleExportPDF}
              disabled={exporting}
              className="px-3 py-2 bg-navy-700 hover:bg-navy-600 border border-navy-500 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 disabled:opacity-50"
              title="Export as PDF"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              {exporting ? "Exporting..." : "PDF"}
            </button>
            <div className={`px-4 py-2 rounded-xl text-center ${oc.bg} ${oc.text}`}>
              <div className="text-2xl font-bold">{overall}</div>
              <div className="text-[10px] font-medium uppercase tracking-wider">Overall</div>
            </div>
          </div>
        </div>

        {/* GHS Pictograms */}
        {ghsPictograms.length > 0 && (
          <div className="mt-4">
            <div className="text-xs text-navy-400 mb-1.5 uppercase tracking-wider font-medium">GHS Pictograms</div>
            <GHSPictogramRow pictogramIds={ghsPictograms} />
          </div>
        )}

        {/* H-phrases with descriptions */}
        <div className="mt-4">
          <button
            onClick={() => setHPhrasesExpanded(!hPhrasesExpanded)}
            className="flex items-center gap-1.5 text-xs text-navy-400 mb-1.5 uppercase tracking-wider font-medium hover:text-navy-200 transition-colors cursor-pointer"
          >
            <span className={`transition-transform inline-block ${hPhrasesExpanded ? 'rotate-90' : ''}`}>▶</span>
            H-Phrases ({hPhrases.length})
          </button>
          <div className="flex flex-wrap gap-1.5">
            {hPhrases.map((h) => {
              const desc = getHPhraseDescription(h);
              return (
                <span
                  key={h}
                  className="px-2 py-0.5 bg-navy-700 border border-navy-600 rounded text-xs font-mono relative group cursor-pointer"
                  onClick={() => setActiveTooltip(activeTooltip === h ? null : h)}
                >
                  {h}
                  {desc && (
                    <span className={`absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2 py-1 bg-navy-900 border border-navy-500 rounded text-xs text-navy-100 whitespace-nowrap transition-opacity z-10 font-sans ${activeTooltip === h ? 'opacity-100' : 'opacity-0 group-hover:opacity-100 pointer-events-none'}`}>
                      {desc}
                    </span>
                  )}
                </span>
              );
            })}
          </div>
          {hPhrasesExpanded && (
            <div className="mt-2 space-y-1 bg-navy-900/50 rounded-lg p-3 border border-navy-700">
              {hPhrases.map((h) => {
                const desc = getHPhraseDescription(h);
                return (
                  <div key={h} className="flex gap-2 text-xs">
                    <span className="font-mono text-navy-300 shrink-0 w-14">{h}</span>
                    <span className="text-navy-200">{desc || "—"}</span>
                  </div>
                );
              })}
            </div>
          )}
        </div>
      </div>

      {/* Scores grid + radar */}
      <div className="mt-4 grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Category scores */}
        <div className="bg-navy-800 border border-navy-600 rounded-2xl p-5">
          <h3 className="text-sm font-semibold text-navy-200 mb-3 uppercase tracking-wider">SSbD Category Scores</h3>
          <div className="space-y-2">
            {CATEGORIES.map(({ key, label, icon }) => {
              const s = scores[key];
              const c = scoreColor(s);
              return (
                <div key={key} className="flex items-center gap-3">
                  <span className="text-base w-6 text-center">{icon}</span>
                  <span className="flex-1 text-sm text-navy-200 truncate">{label}</span>
                  <div className="flex gap-0.5">
                    {[1, 2, 3, 4, 5].map((v) => (
                      <div
                        key={v}
                        className={`w-6 h-6 rounded text-xs font-bold flex items-center justify-center transition-all ${
                          v <= s
                            ? `${c.bg} ${c.text}`
                            : "bg-navy-700 text-navy-500"
                        }`}
                      >
                        {v}
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Radar chart */}
        <div className="bg-navy-800 border border-navy-600 rounded-2xl p-5 flex items-center justify-center radar-chart-container">
          <RadarChart chemicals={[chemical]} />
        </div>
      </div>
    </div>
  );
}
