import { useState, useRef } from "react";
import { CATEGORIES, scoreColor } from "../data/scoring";
import { getHPhraseDescription } from "../data/ghsData";
import RadarChart from "./RadarChart";

async function exportComparePDF(chemicals, containerRef) {
  const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
    import("jspdf"),
    import("html2canvas"),
  ]);

  const pdf = new jsPDF("p", "mm", "a4");
  const w = pdf.internal.pageSize.getWidth();
  const margin = 15;
  let y = 15;

  pdf.setFontSize(16);
  pdf.setFont(undefined, "bold");
  pdf.text("ChemScreen — Comparison Report", margin, y);
  y += 8;

  pdf.setFontSize(10);
  pdf.setFont(undefined, "normal");
  pdf.setTextColor(100);
  pdf.text(chemicals.map((c) => `${c.name} (${c.cas})`).join("  vs  "), margin, y);
  y += 10;

  // Scores table
  pdf.setTextColor(0);
  pdf.setFontSize(11);
  pdf.setFont(undefined, "bold");
  pdf.text("Category Scores", margin, y);
  y += 7;

  pdf.setFontSize(9);
  pdf.setFont(undefined, "normal");

  // Header row
  let colW = (w - margin * 2 - 60) / chemicals.length;
  pdf.setFont(undefined, "bold");
  pdf.text("Category", margin, y);
  chemicals.forEach((c, i) => {
    pdf.text(c.name.substring(0, 18), margin + 60 + i * colW, y);
  });
  y += 5;
  pdf.setFont(undefined, "normal");

  CATEGORIES.forEach(({ key, label }) => {
    pdf.text(label, margin, y);
    chemicals.forEach((c, i) => {
      pdf.text(`${c.scores[key]}/5`, margin + 60 + i * colW, y);
    });
    y += 5;
  });
  y += 2;
  pdf.setFont(undefined, "bold");
  pdf.text("Overall", margin, y);
  chemicals.forEach((c, i) => {
    pdf.text(`${c.overall}/5`, margin + 60 + i * colW, y);
  });
  y += 10;

  // Radar chart
  try {
    const radarEl = containerRef.current?.querySelector(".compare-radar-container");
    if (radarEl) {
      const canvas = await html2canvas(radarEl, { backgroundColor: "#0f172a", scale: 2 });
      const imgData = canvas.toDataURL("image/png");
      if (y > 160) { pdf.addPage(); y = 15; }
      const imgW = 120;
      const imgH = (canvas.height / canvas.width) * imgW;
      pdf.addImage(imgData, "PNG", (w - imgW) / 2, y, imgW, imgH);
      y += imgH + 8;
    }
  } catch (e) {}

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(`Generated by ChemScreen — ${new Date().toLocaleDateString("sv-SE")}`, margin, 285);

  pdf.save(`ChemScreen_Compare_${chemicals.map((c) => c.name.replace(/[^a-zA-Z0-9]/g, "")).join("_vs_")}.pdf`);
}

export default function CompareView({ chemicals }) {
  const [exporting, setExporting] = useState(false);
  const containerRef = useRef(null);

  async function handleExport() {
    setExporting(true);
    try { await exportComparePDF(chemicals, containerRef); } catch (e) { console.error(e); }
    setExporting(false);
  }

  return (
    <div className="mt-6 animate-fadeIn" ref={containerRef}>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold">Comparison — {chemicals.map((c) => c.name).join(" vs ")}</h2>
        <button
          onClick={handleExport}
          disabled={exporting}
          className="px-3 py-2 bg-navy-700 hover:bg-navy-600 border border-navy-500 rounded-lg text-xs font-medium transition-colors flex items-center gap-1.5 disabled:opacity-50"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          {exporting ? "Exporting..." : "Export PDF"}
        </button>
      </div>

      {/* Radar */}
      <div className="bg-navy-800 border border-navy-600 rounded-2xl p-6 flex justify-center mb-4 compare-radar-container">
        <div className="w-full max-w-md">
          <RadarChart chemicals={chemicals} />
        </div>
      </div>

      {/* Table */}
      <div className="bg-navy-800 border border-navy-600 rounded-2xl overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-navy-600">
              <th className="text-left p-3 text-navy-400 font-medium">Category</th>
              {chemicals.map((c) => (
                <th key={c.cas} className="p-3 text-center font-medium">
                  <div>{c.name}</div>
                  <div className="text-xs text-navy-400 font-mono font-normal">{c.cas}</div>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {CATEGORIES.map(({ key, label, icon }) => (
              <tr key={key} className="border-b border-navy-700/50">
                <td className="p-3 text-navy-200">
                  <span className="mr-2">{icon}</span>{label}
                </td>
                {chemicals.map((c) => {
                  const s = c.scores[key];
                  const sc = scoreColor(s);
                  return (
                    <td key={c.cas} className="p-3 text-center">
                      <span className={`inline-block px-2.5 py-1 rounded-lg font-bold text-sm ${sc.bg} ${sc.text}`}>
                        {s}
                      </span>
                    </td>
                  );
                })}
              </tr>
            ))}
            <tr className="bg-navy-700/30">
              <td className="p-3 font-semibold">Overall</td>
              {chemicals.map((c) => {
                const sc = scoreColor(c.overall);
                return (
                  <td key={c.cas} className="p-3 text-center">
                    <span className={`inline-block px-3 py-1 rounded-lg font-bold ${sc.bg} ${sc.text}`}>
                      {c.overall}
                    </span>
                  </td>
                );
              })}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
